### ISSUE TITLE
Librarian Archive Template

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/ccl#58]
Should be a sortable list by Name and Subject. Default to Subject sorting.

**Comment by kpettinga** [comment]
@gabrielo-cuc I'm running into an issue creating an archive for Librarians. On the old site, each librarian only has one subject associated with him/her (http://libraries.claremont.edu/contact/directories/librarians.asp). With the data that we've imported from LibGuides, however, some librarians have **more than 10** subjects assigned to them. 

So the question is, when a librarian has more than 1 subject, which do we use for sorting purposes? Likewise, when a librarian has NO subjects (which there are some) where do they fall in the sorted list?

**Comment by gabriel-ortiz** [comment]
@kpettinga Let's display all the subjects for each librarian. It's important in our efforts to ensure that users recognize the ubiquitousness of our librarians. So it's vital for us to list all the various ways librarians can offer support. It's possible that some subjects listed are not pertinent, and we can remove some.

How are the librarians currently organized on the archive page? Is there a page we can see? We basically have 2 options. Organize the archive page alphabetically by subject, or by librarian name. In my opinion, it's more important to sort by subject- because it will be more task oriented. This probably means that librarian data with be repeated throughout the page, which is fine - I've seen other libraries do this.

For the people we have no subjects - we should double check on whether they are either librarians, or staff. If they are staff, we will need to filter them out somehow. Can you give me a couple names?

**Comment by kpettinga** [comment]
@gabrielo-cuc check out the latest work on the librarian template at http://libraryweb.wpengine.com/librarians/

I've set the default to display by subject as well as added an accordion which lists all subjects that can be clicked to auto-scroll directly to that subject/librarian. 

Because many librarians have multiple subjects associated with them, some librarians appear more than once.

In addition, I've added a **Staff Role** taxonomy which is being used to differentiate librarians from "regular" staff.

**Comment by gabriel-ortiz** [comment]
@kpettinga This is looking solid - It covers all the methods that users might use to filter through librarians. Nicely done man.

- When listing librarians by subject, is it possible to only show them once with their respected subjects? I know this is still being refined - so sorry if I'm mentioning something you already had in queue.

- The librarians by name is on-point though!

- Per staff roles: yea that taxonomy will help big time. because we still want a staff roster page where librarian and non-librarian staff will appear together

- One UI tweak to consider. Could we incorporate some way of indicating the librarian profile box when a subject is scrolled to? Maybe like a temporary highlight background color that fades out... IDK.. just some thoughts

**Comment by kpettinga** [comment]
hey @gabrielo-cuc 

> When listing librarians by subject, is it possible to only show them once with their respected subjects? I know this is still being refined - so sorry if I'm mentioning something you already had in queue.

This is the logic problem I was trying to bring up initially. If a librarian has more than 1 subject associated with them, and you only want librarians to show up once, what subject do they get listed in?

> staff roles

There's a taxonomy for staff roles now that can be used to categorize everyone. The librarian archive template is set to gather people with the "librarian" term.

> UI tweak:

I think we may need to just figure out a better hierarchy between the labels for each subject and the librarians that belong to them. We will come up with something and get back to you.

**Comment by gabriel-ortiz** [comment]
@kpettinga What about listing the librarians alphabetically, and also offering a big list of subjects that act as achortags that link to the corresponding library profile? This addresses the issuing of librarians repeating multiple times when listed by subject. It also kinda simplifies the UI too.

**Comment by kpettinga** [comment]
@gabrielo-cuc that could work BUT there are a few subjects where there is more than 1 librarian, which would mean creating the same ID for two librarian profiles on a page, which is a big accessibility "no-no".

**Comment by gabriel-ortiz** [comment]
@kpettinga Valid Point. We have a committee meeting today and lemme kick it up to them and we'll discuss our options. I will get back to you by EOD. Thanks man

**Comment by gabriel-ortiz** [comment]
@kpettinga by bad for not getting back on this sooner - So our team chatted about this and would like all of us to consider the following recommendation: can we have 2 layouts -1) with librarians organized by name; the way we have it now - and 2) a layout by ssubject in a table format, ie  http://www.library.ucla.edu/support/research-help/contact-subject-librarian . A table layout in this case will allow us to repeat librarian data without looking obtrusive. Thoughts?

**Comment by kpettinga** [comment]
@gabrielo-cuc I've created a a table view for the subject list. Let us know if this works.
